### ISSUE TITLE
RuntimeError: Unknown sync type 3800c83f on Windows 10

### ISSUE THREAD

**Issue by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [39aldo39/Radicale-DecSync#12]
I set up Radicale DecSync with default values given in [README.md](https://github.com/39aldo39/Radicale-DecSync/blob/master/README.md). Radicale works fine without DecSync storage plugin.

> C:\Users\Laptop>"C:\Program Files\Python39\python.exe" -m radicale --config "~/.config/radicale/config" --debug

```
[2021-03-16 10:26:01 +0100] [8156] [INFO] Loaded default config
[2021-03-16 10:26:01 +0100] [8156] [INFO] Loaded config file 'C:\\Users\\Laptop\\.config\\radicale\\config'
[2021-03-16 10:26:01 +0100] [8156] [INFO] Loaded arguments
[2021-03-16 10:26:01 +0100] [8156] [INFO] Starting Radicale
[2021-03-16 10:26:01 +0100] [8156] [INFO] auth type is 'radicale.auth.none'
[2021-03-16 10:26:01 +0100] [8156] [INFO] storage type is 'radicale_storage_decsync'
[2021-03-16 10:26:01 +0100] [8156] [INFO] rights type is 'radicale.rights.owner_only'
[2021-03-16 10:26:01 +0100] [8156] [INFO] web type is 'radicale.web.internal'
[2021-03-16 10:26:01 +0100] [8156] [INFO] Listening on '[127.0.0.1]:5232'
[2021-03-16 10:26:01 +0100] [8156] [INFO] Listening on '[::1]:5232'
[2021-03-16 10:26:01 +0100] [8156] [INFO] Radicale server ready
[2021-03-16 10:26:05 +0100] [8156/Thread-1] [INFO] GET request for '/' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:05 +0100] [8156/Thread-1] [DEBUG] Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'document',
 'HTTP_SEC_FETCH_MODE': 'navigate',
 'HTTP_SEC_FETCH_SITE': 'none',
 'HTTP_SEC_FETCH_USER': '?1',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=796>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:05 +0100] [8156/Thread-1] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:05 +0100] [8156/Thread-1] [DEBUG] Sanitized path: '/'
[2021-03-16 10:26:05 +0100] [8156/Thread-1] [DEBUG] Response content:
Redirected to .web
[2021-03-16 10:26:05 +0100] [8156/Thread-1] [INFO] GET response status for '/' in 0.004 seconds: 302 Found
[2021-03-16 10:26:05 +0100] [8156/Thread-2] [INFO] GET request for '/.web' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:05 +0100] [8156/Thread-2] [DEBUG] Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'document',
 'HTTP_SEC_FETCH_MODE': 'navigate',
 'HTTP_SEC_FETCH_SITE': 'none',
 'HTTP_SEC_FETCH_USER': '?1',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/.web',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=844>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:05 +0100] [8156/Thread-2] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:05 +0100] [8156/Thread-2] [DEBUG] Sanitized path: '/.web'
[2021-03-16 10:26:05 +0100] [8156/Thread-2] [DEBUG] Response content:
Redirected to .web/
[2021-03-16 10:26:05 +0100] [8156/Thread-2] [INFO] GET response status for '/.web' in 0.007 seconds: 302 Found
[2021-03-16 10:26:05 +0100] [8156/Thread-3] [INFO] GET request for '/.web/' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:05 +0100] [8156/Thread-3] [DEBUG] Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'document',
 'HTTP_SEC_FETCH_MODE': 'navigate',
 'HTTP_SEC_FETCH_SITE': 'none',
 'HTTP_SEC_FETCH_USER': '?1',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/.web/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=872>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:05 +0100] [8156/Thread-3] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:05 +0100] [8156/Thread-3] [DEBUG] Sanitized path: '/.web/'
[2021-03-16 10:26:05 +0100] [8156/Thread-3] [INFO] GET response status for '/.web/' in 0.012 seconds: 200 OK
[2021-03-16 10:26:05 +0100] [8156/Thread-4] [INFO] GET request for '/.web/fn.js' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:05 +0100] [8156/Thread-4] [DEBUG] Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_REFERER': 'http://localhost:5232/.web/',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'script',
 'HTTP_SEC_FETCH_MODE': 'no-cors',
 'HTTP_SEC_FETCH_SITE': 'same-origin',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/.web/fn.js',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=880>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:05 +0100] [8156/Thread-4] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:05 +0100] [8156/Thread-5] [INFO] GET request for '/.web/css/main.css' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:05 +0100] [8156/Thread-4] [DEBUG] Sanitized path: '/.web/fn.js'
[2021-03-16 10:26:05 +0100] [8156/Thread-5] [DEBUG] Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/css,*/*;q=0.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_REFERER': 'http://localhost:5232/.web/',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'style',
 'HTTP_SEC_FETCH_MODE': 'no-cors',
 'HTTP_SEC_FETCH_SITE': 'same-origin',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/.web/css/main.css',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=848>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:05 +0100] [8156/Thread-4] [INFO] GET response status for '/.web/fn.js' in 0.018 seconds: 200 OK
[2021-03-16 10:26:05 +0100] [8156/Thread-5] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:05 +0100] [8156/Thread-5] [DEBUG] Sanitized path: '/.web/css/main.css'
[2021-03-16 10:26:05 +0100] [8156/Thread-5] [INFO] GET response status for '/.web/css/main.css' in 0.012 seconds: 200 OK
[2021-03-16 10:26:05 +0100] [8156/Thread-6] [INFO] GET request for '/.web/css/icon.png' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:05 +0100] [8156/Thread-6] [DEBUG] Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_REFERER': 'http://localhost:5232/.web/',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'image',
 'HTTP_SEC_FETCH_MODE': 'no-cors',
 'HTTP_SEC_FETCH_SITE': 'same-origin',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/.web/css/icon.png',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=928>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:05 +0100] [8156/Thread-6] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:05 +0100] [8156/Thread-6] [DEBUG] Sanitized path: '/.web/css/icon.png'
[2021-03-16 10:26:05 +0100] [8156/Thread-6] [INFO] GET response status for '/.web/css/icon.png' in 0.018 seconds: 200 OK
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [INFO] PROPFIND request for '/' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [DEBUG] Request headers:
{'CONTENT_LENGTH': '127',
 'CONTENT_TYPE': 'text/plain;charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_ORIGIN': 'http://localhost:5232',
 'HTTP_REFERER': 'http://localhost:5232/.web/',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'empty',
 'HTTP_SEC_FETCH_MODE': 'cors',
 'HTTP_SEC_FETCH_SITE': 'same-origin',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=936>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [DEBUG] Sanitized path: '/'
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [DEBUG] Request content:
<?xml version="1.0"?>
<propfind xmlns="DAV:">
  <prop>
    <current-user-principal />
    <displayname />
  </prop>
</propfind>

[2021-03-16 10:26:10 +0100] [8156/Thread-7] [INFO] Access to '/' denied for anonymous user
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [DEBUG] Asking client for authentication
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [DEBUG] Response content:
Access to the requested resource forbidden.
[2021-03-16 10:26:10 +0100] [8156/Thread-7] [INFO] PROPFIND response status for '/' in 0.024 seconds: 401 Unauthorized
[2021-03-16 10:26:10 +0100] [8156/Thread-8] [INFO] PROPFIND request for '/' received from ::1 using 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
[2021-03-16 10:26:10 +0100] [8156/Thread-8] [DEBUG] Request headers:
{'CONTENT_LENGTH': '127',
 'CONTENT_TYPE': 'text/plain;charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'de-DE,de;q=0.9',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_ORIGIN': 'http://localhost:5232',
 'HTTP_REFERER': 'http://localhost:5232/.web/',
 'HTTP_SEC_CH_UA': '"Google Chrome";v="89", "Chromium";v="89", ";Not A '
                   'Brand";v="99"',
 'HTTP_SEC_CH_UA_MOBILE': '?0',
 'HTTP_SEC_FETCH_DEST': 'empty',
 'HTTP_SEC_FETCH_MODE': 'cors',
 'HTTP_SEC_FETCH_SITE': 'same-origin',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/89.0.4389.82 Safari/537.36',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Laptop',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=820>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[2021-03-16 10:26:10 +0100] [8156/Thread-8] [DEBUG] Sanitized script name: ''
[2021-03-16 10:26:10 +0100] [8156/Thread-8] [DEBUG] Sanitized path: '/'
[2021-03-16 10:26:10 +0100] [8156/Thread-8] [INFO] Successful login: 'root'
[2021-03-16 10:26:10 +0100] [8156/Thread-8] [ERROR] An exception occurred during PROPFIND request on '/': Unknown sync type 3800c83f
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\radicale\app\__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "C:\Program Files\Python39\lib\site-packages\radicale\app\__init__.py", line 250, in _handle_request
    principal = next(self._storage.discover(
  File "C:\Program Files\Python39\lib\site-packages\radicale_storage_decsync\__init__.py", line 159, in discover
    collections = list(super().discover(path, depth, child_context_manager))
  File "C:\Program Files\Python39\lib\site-packages\radicale\storage\multifilesystem\discover.py", line 84, in discover
    yield self._collection_class(self, child_path)
  File "C:\Program Files\Python39\lib\site-packages\radicale_storage_decsync\__init__.py", line 57, in __init__
    raise RuntimeError("Unknown sync type " + sync_type)
RuntimeError: Unknown sync type 3800c83f
```

**Comment by purlupar** [comment]
I've fixed this in my case: In the radicale setup web interface, make the collection be "calendar and tasks". In my case it was calendars, which made the path look like /username/abcd-abcd-abcd instead of /username/calendars-abcd-abcd-abcd. Radicale-decsync then took the first string before the dash as the "type", thus we got the "unknown type 3800c83f" error. You might need to remove the decsync_dir and sync_type in the .config/radicale/config, then login to radicale, remove the collection, and make a new one as describe above. Then add the stuff back into the config.

**Comment by 39aldo39** [comment]
I see, you created the collection without the DecSync plugin as the plugin will always add a `calendars-` or `contacts-` prefix. I should probably take more care for that case.
