### ISSUE TITLE
exception: access violation reading 0x0000000000000008 when importing ICS files

### ISSUE THREAD

**Issue by tomasz1986** [39aldo39/Radicale-DecSync#6]
When trying import ICS files exported from Radicale into Thunderbird, I get a lot of these errors.

```
DecSync: Write 1 entry
[2020-08-18 00:53:37 +0900] [1904/Thread-349] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/8dd0abc2-49c5-428e-874f-c5b99849b885.ics': exception: access violation reading 0x0000000000000008
[2020-08-18 00:53:37 +0900] [1904/Thread-350] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/8e134db9-3fad-4cf4-bb4d-ec1a3f3ba142.ics': exception: access violation reading 0x0000000000000008
[2020-08-18 00:53:37 +0900] [1904/Thread-348] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/8d1383bea60625a.ics': exception: access violation reading 0x0000000000000008
[2020-08-18 00:53:37 +0900] [1904/Thread-351] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/8e3ce5a5-bf6d-4665-9c29-eb204ca7b801.ics': exception: access violation reading 0x0000000000000008
DecSync: Write 1 entry
DecSync: Write 1 entry
DecSync: Write 1 entry
DecSync: Write 1 entry
DecSync: Write 1 entry
DecSync: Write 1 entry
[2020-08-18 00:53:39 +0900] [1904/Thread-360] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/92bd2537-3509-4208-b240-ca0c14c10a89.ics': exception: access violation reading 0x0000000000000008
[2020-08-18 00:53:39 +0900] [1904/Thread-361] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/92eefb4c-dac6-4f91-9c7b-f4ecd06f1cb8.ics': exception: access violation reading 0x0000000000000008
[2020-08-18 00:53:39 +0900] [1904/Thread-362] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/92g7e9pcjtuam0vjb6mpecm7to@google.com.ics': exception: access violation reading 0x0000000000000008
[2020-08-18 00:53:39 +0900] [1904/Thread-358] [ERROR] An exception occurred during PUT request on '/tomasz86/calendars-919aba81-6c8f-6325-b83f-9946e56de5ef/917298ce-f4f5-4e70-801e-65111f7b87ea.ics': exception: access violation reading 0x0000000000000008
DecSync: Write 1 entry
```

Do you have any idea what may be the cause of it?

**Comment by 39aldo39** [comment]
Thanks for the report! I don't the cause of it, maybe restarting Radicale helps? I am also surprised by the errors, as it is strange that it trying to read from 0x08. The null pointer in 0x00 would be more logical, but even that I have never seen before.

**Comment by tomasz1986** [comment]
I have tried multiple times. Restarting makes no difference, unfortunately. The errors always show up as soon as I try to import any of the ICS files.

**Comment by tomasz1986** [comment]
I am sorry for the delay. I think that I have managed to grab the error with `--debug` enabled.

```
[2020-10-03 09:27:45 +0900] [5344/Thread-263] [INFO] DELETE response status for '/tomasz86/calendars-dca9ca70-bc39-acdd-e93d-f310f8fa2a91/02e45e91-9300-4314-96ea-e3f4a943ddbf.ics' in 0.925 seconds: 200 OK
[2020-10-03 09:27:45 +0900] [5344/Thread-269] [ERROR] An exception occurred during DELETE request on '/tomasz86/calendars-dca9ca70-bc39-acdd-e93d-f310f8fa2a91/691f1861-e696-45f1-9af6-18c1a35ff3b2.ics': exception: access violation reading 0x0000000000000008
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale\app\__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale\app\__init__.py", line 250, in _handle_request
    principal = next(self._storage.discover(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale_storage_decsync\__init__.py", line 152, in discover
    collections = list(super().discover(path, depth, child_context_manager))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale\storage\multifilesystem\discover.py", line 84, in discover
    yield self._collection_class(self, child_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale_storage_decsync\__init__.py", line 60, in __init__
    self.decsync = Decsync(decsync_dir, sync_type, collection, own_app_id)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\libdecsync\__init__.py", line 279, in __init__
    _decsync_new_c(byref(self.ptr), decsync_dir.encode(), sync_type.encode(), collection.encode(), own_app_id.encode())
OSError: exception: access violation reading 0x0000000000000008
[2020-10-03 09:27:45 +0900] [5344/Thread-271] [ERROR] An exception occurred during DELETE request on '/tomasz86/calendars-dca9ca70-bc39-acdd-e93d-f310f8fa2a91/cde28e8d-3ea7-4495-8387-13b21ed9e896.ics': exception: access violation reading 0x0000000000000008
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale\app\__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale\app\__init__.py", line 250, in _handle_request
    principal = next(self._storage.discover(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale_storage_decsync\__init__.py", line 152, in discover
    collections = list(super().discover(path, depth, child_context_manager))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale\storage\multifilesystem\discover.py", line 84, in discover
    yield self._collection_class(self, child_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\radicale_storage_decsync\__init__.py", line 60, in __init__
    self.decsync = Decsync(decsync_dir, sync_type, collection, own_app_id)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\libdecsync\__init__.py", line 279, in __init__
    _decsync_new_c(byref(self.ptr), decsync_dir.encode(), sync_type.encode(), collection.encode(), own_app_id.encode())
OSError: exception: access violation reading 0x0000000000000008
````

**Comment by 39aldo39** [comment]
Thanks for the log! Could you also check the version of the `libdecsync` Python package? There are significant changes made in the meantime, especially in version v1.7.0. You can upgrade by executing `pip3 install -U libdecsync`.

**Comment by tomasz1986** [comment]
I have now managed to come back to the issue. First of all, `libdecsync` was indeed old, so I have updated everything to the newest versions right now.

However, when trying to import any ICS file with the current version of the plugin, the result is
```
[2021-01-11 16:13:42 +0900] [27916/Thread-65] [WARNING] Bad PUT request on '/tomasz86/calendars-bd973618-6430-2a5a-0d79-7deaa38c9432/': Uploading a whole collection is currently not supported with the DecSync plugin
```

which I guess is due to

https://github.com/39aldo39/Radicale-DecSync/blob/064cb168e93a574ed24732e1ef3cbb771c9c6d5f/radicale_storage_decsync/__init__.py#L213-L214

Does this mean that importing an ICS file with multiple entries is no longer possible? The ICS files that I am trying to import all have been exported from Radicale. If that is the case, then is there any way to import multiple ICS files to DecSync at once? Thunderbird only allows importing 1 ICS file at a time, which is a no-go in this case. I do have everything split into single ICS files through Radicale, but is there any way to import or transfer this to DecSync?

**Comment by 39aldo39** [comment]
How do you import the ICS file? If I import one using Thunderbird it will (implicitly) import the events one by one and works fine.

**Comment by tomasz1986** [comment]
I have tried importing using both Thunderbird, and also the Radicale GUI. In both cases, the same error pops up, and at the end no events get imported.

**Comment by tomasz1986** [comment]
I have done some more testing today, and importing seems to be working now. Trying to upload a calendar or an address book using the Radicale Web GUI still fails with the same error complaining about "uploading a whole collection", but importing directly with Thunderbird seems to be working fine.

Importing each entry is accompanied by the following error though.

```
[ERROR] An exception occurred during PUT request on '/test/contacts-c8e2d113-89c6-fafd-f146-c06b99469fff/c8f273ee-784b-4df7-bbb1-a545c7326197.vcf': 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\radicale\app\__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "C:\Program Files\Python39\lib\site-packages\radicale\app\__init__.py", line 276, in _handle_request
    status, headers, answer = function(
  File "C:\Program Files\Python39\lib\site-packages\radicale\app\put.py", line 210, in do_PUT
    etag = parent_item.upload(href, prepared_item).etag
  File "C:\Program Files\Python39\lib\site-packages\radicale_storage_decsync\__init__.py", line 99, in upload
    supported_components = self.get_meta("C:supported-calendar-component-set").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

However, the entries themselves seem to be imported correctly in the end, so I am not sure what the error is exactly about.

**Comment by tomasz1986** [comment]
I am writing back, because I was wrong yesterday. What I wrote above is still correct, but only for importing contacts. When trying to import calendars though, the error is still present.

This is an example of a minimal ICS file that I have been trying to import.

```
BEGIN:VCALENDAR
BEGIN:VEVENT
UID:9203c45f-64e8-4c79-aa41-0376103450e7
DTSTART:20210205T125805Z
DTEND:20210205T125856Z
DTSTAMP:20210205T125856Z
SUMMARY:test
DESCRIPTION:test
END:VEVENT
END:VCALENDAR
```

and it fails with

```
[WARNING] Bad PUT request on '/tw86/calendars-d5a025d9-815b-3623-d6b2-29f5e2da0f8e/': Uploading a whole collection is currently not supported with the DecSync plugin
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\radicale\app\put.py", line 194, in do_PUT
    etag = self._storage.create_collection(
  File "C:\Program Files\Python39\lib\site-packages\radicale_storage_decsync\__init__.py", line 214, in create_collection
    raise ValueError("Uploading a whole collection is currently not supported with the DecSync plugin")
ValueError: Uploading a whole collection is currently not supported with the DecSync plugin
```
.
